# TODO: add redis and elastic and options to shopware
#
version: "3.8"
volumes:
  shopware-themes: {}
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopware
      MYSQL_USER: shopware
      MYSQL_PASSWORD: shopware
  sangross:
    build: ./SangrossMockService/
  shopware:
    build: .
    environment:
      APP_SECRET: 440dec3766de53010c5ccf6231c182acfc90bd25cff82e771245f736fd276518
      INSTANCE_ID: 10612e3916e153dd3447850e944a03fabe89440970295447a30a75b151bd844e
      APP_URL: "http://localhost"
      DATABASE_HOST: mysql
      DATABASE_URL: "mysql://shopware:shopware@mysql:3306/shopware"
      SANGROSS_URL: "http://sangross:8000/"
      INSTALL_LOCALE: de-DE
      INSTALL_CURRENCY: EUR
      INSTALL_ADMIN_USERNAME: admin
      INSTALL_ADMIN_PASSWORD: shopware
      TZ: Europe/Berlin
      ACTIVE_PLUGINS: "LigoSangrossAdapter LigoShopThemeV1"
    volumes:
      - shopware-themes:/var/www/html/public/theme:rw
    ports:
      - 80:80
