# TODO: add redis and elastic and options to shopware
#
version: "3.8"

# TODO: volumes
# "/state": {},
# "/var/www/html/config/jwt": {},
# "/var/www/html/custom/plugins": {},
# "/var/www/html/files": {},
# "/var/www/html/public/bundles": {},
# "/var/www/html/public/media": {},
# "/var/www/html/public/sitemap": {},
# "/var/www/html/public/theme": {},
# "/var/www/html/public/thumbnail": {},
# "/var/www/html/var/log": {}

volumes:
  shopware-themes: {}

services:
  redis:
    image: "redis:6.2"

  mail:
    image: "mailhog/mailhog:latest"
    ports:
      - "8025:8025"

  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopware
      MYSQL_USER: shopware
      MYSQL_PASSWORD: shopware

  sangross:
    build: ./test/SangrossMockService/

  # todo: env variables
  #  "APP_SECRET=440dec3766de53010c5ccf6231c182acfc90bd25cff82e771245f736fd276518",
  #  "APP_URL=http://localhost",
  #  "TZ=Europe/Berlin",
  #  "ACTIVE_PLUGINS=SangrossAdapter LigoShopThemeV1",
  #  "INSTALL_ADMIN_USERNAME=admin",
  #  "INSTALL_CURRENCY=EUR",
  #  "DATABASE_HOST=mysql",
  #  "DATABASE_URL=mysql://shopware:shopware@mysql:3306/shopware",
  #  "INSTALL_LOCALE=de-DE",
  #  "INSTALL_ADMIN_PASSWORD=shopware",
  #  "INSTANCE_ID=10612e3916e153dd3447850e944a03fabe89440970295447a30a75b151bd844e",
  #  "SANGROSS_URL=http://sangross:8000/",
  #  "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
  #  "APP_ENV=prod",
  #  "MAILER_URL=null://localhost",
  #  "SHOPWARE_ES_HOSTS=",
  #  "SHOPWARE_ES_ENABLED=0",
  #  "SHOPWARE_ES_INDEXING_ENABLED=0",
  #  "SHOPWARE_ES_INDEX_PREFIX=",
  #  "COMPOSER_HOME=/tmp/composer",
  #  "SHOPWARE_HTTP_CACHE_ENABLED=1",
  #  "SHOPWARE_HTTP_DEFAULT_TTL=7200",
  #  "SHOPWARE_AUTOMATICALLY_EMPTY_CACHE_ENABLED=false",
  #  "SHOPWARE_EMPTY_CACHE_INTERVAL=86400",
  #  "BLUE_GREEN_DEPLOYMENT=1",
  #  "CACHE_ADAPTER=default",
  #  "REDIS_CACHE_HOST=redis",
  #  "REDIS_CACHE_PORT=6379",
  #  "REDIS_CACHE_DATABASE=0",
  #  "SESSION_ADAPTER=default",
  #  "REDIS_SESSION_HOST=redis",
  #  "REDIS_SESSION_PORT=6379",
  #  "REDIS_SESSION_DATABASE=1",
  #  "FPM_PM=dynamic",
  #  "FPM_PM_MAX_CHILDREN=5",
  #  "FPM_PM_START_SERVERS=2",
  #  "FPM_PM_MIN_SPARE_SERVERS=1",
  #  "FPM_PM_MAX_SPARE_SERVERS=3",
  #  "PHP_MAX_UPLOAD_SIZE=128m",
  #  "PHP_MAX_EXECUTION_TIME=300",
  #  "PHP_MEMORY_LIMIT=512m",
  #  "LD_PRELOAD=/usr/lib/preloadable_libiconv.so php"
  shopware:
    build: .
    environment:
      APP_SECRET: 440dec3766de53010c5ccf6231c182acfc90bd25cff82e771245f736fd276518
      INSTANCE_ID: 10612e3916e153dd3447850e944a03fabe89440970295447a30a75b151bd844e
      APP_URL: "http://localhost"
      APP_ENV: dev
      MAILER_URL: "smtp://mail:1025"
      DATABASE_HOST: mysql
      DATABASE_URL: "mysql://shopware:shopware@mysql:3306/shopware"
      CACHE_ADAPTER: default
      REDIS_CACHE_HOST: redis
      REDIS_CACHE_PORT: 6379
      REDIS_CACHE_DATABASE: 1
      SESSION_ADAPTER: default
      REDIS_SESSION_HOST: redis
      REDIS_SESSION_PORT: 6379
      REDIS_SESSION_DATABASE: 1
      INSTALL_LOCALE: de-DE
      INSTALL_CURRENCY: EUR
      INSTALL_ADMIN_USERNAME: admin
      INSTALL_ADMIN_PASSWORD: shopware
      SHOPWARE_HTTP_CACHE_ENABLED: 0
      TZ: Europe/Berlin
      ACTIVE_PLUGINS: "SangrossAdapter LigoShopThemeV1"
      SANGROSS_URL: "http://sangross:8000/"
    volumes:
      - shopware-themes:/var/www/html/public/theme:rw
    ports:
      - "80:80"
